version: '3'

services:
  arch-machine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arch-machine
    network_mode: host
    volumes:
      - arch-home:/home/naruto/

volumes:
  arch-home:
    driver: local
